### ISSUE TITLE
The thread running the “cpmi.commit(cvimg(image))“ command in the perf() function is blocked by get().

### ISSUE THREAD

**Issue by ghmchen** [shouxieai/infer#9]
Hello,
In perf() function, it looks like we have to do future get() after each commit.
It means the thread running the “cpmi.commit(cvimg(image))“ command is blocked by get().
For example, the following codes works:
std::vector<std::shared_future<yolo::BoxArray>> outputs;
for (int idx = 0; idx < files.size(); ++idx) {
auto image = cv::imread(files[idx]);		
auto fu = cpmi.commit(cvimg(image));
outputs.emplace_back(fu);
auto objs = outputs[idx].get();	//we can get the objs result successfully 	
};
The following codes do not work:
std::vector<std::shared_future<yolo::BoxArray>> outputs;
for (int idx = 0; idx < files.size(); ++idx) {
auto image = cv::imread(files[idx]);		
auto fu = cpmi.commit(cvimg(image));
outputs.emplace_back(fu);	
};
auto objs = outputs[0].get();	//we cannot get correct objs result here !!! , it will have 0 or a random size.
Any suggestion if I want use another thread to manipulate the post-processed inference results? Thanks.

**Comment by shouxieai** [comment]
It shouldn't have a 0 or random size issue. I need to reproduce it to try.

**Comment by shouxieai** [comment]
The commit function just adds your image pointer to the queue. It does not store a copy of the image. You need to ensure that the committed image is not destroyed before calling future.get() to get the result, otherwise undefined behavior will occur. In your code, since the image comes from imread(), the image is destroyed when outputs.emplace_back(fu) is called. This will get an invalid pointer in cpm.

**Comment by ghmchen** [comment]
@shouxieai Yes, just as you said. I can get expected results now. You are super!
